In [2]:
#coding=utf-8
import pandas as pd 
df = pd.read_csv('/Users/xiefei/Desktop/test', sep = '\t')

In [3]:
df.head()

,id,tags,user_id,pt,created_at,duotou_reject_reson,strategy_name,qdscore,qdscore_level,duotou_score,loan_money,iou_limit,type
0,3598924384,QD-600U-accept-radical-allorder-all,4424852,2018-01-23_07,2018-01-23 07:42:54,用户Android多头平台数拦截,用户多头模型回捞,964,A1,780.0,1400.0,3410.00,month
1,3599739198,A5_noduotou_random_callback,1019932,2018-01-23_12,2018-01-23 12:53:01,用户QD分层条件拦截,用户多头回捞测试,825,A5,697.0,900.0,2399.94,week
2,3599739198,QD-600U-accept-conservative-allorder-hold,1019932,2018-01-23_12,2018-01-23 12:53:01,用户QD分层条件拦截,用户多头回捞测试,825,A5,697.0,900.0,2399.94,week
3,3599831719,amountup_marketing,8786041,2018-01-23_13,2018-01-23 13:29:52,用户Android多头平台数拦截,用户多头模型回捞,932,A2,755.0,900.0,3523.24,month
4,3599831719,amountup_wednesday_memberday,8786041,2018-01-23_13,2018-01-23 13:29:52,用户Android多头平台数拦截,用户多头模型回捞,932,A2,755.0,900.0,3523.24,month

In [4]:
a = df[df['tags'].isin(["A1_duotou_callback_720_749"
                        ,"A1_duotou_callback_ge_750"
                        ,"A1_duotou_random_callback"
                        ,"A2_duotou_callback_720_749"
                        ,"A2_duotou_callback_ge_750"
                        ,"A2_duotou_random_callback"
                        ,"A3_duotou_callback_720_754"
                        ,"A3_duotou_callback_ge_755"
                        ,"A3_duotou_random_callback"
                        ,"A4_duotou_callback_720_749"
                        ,"A4_duotou_random_callback"
                        ,"A4_duotou_callback_ge_750"
                        ,"A5_noduotou_callback_720_769"
                        ,"A5_noduotou_callback_ge_770"
                        ,"A5_noduotou_random_callback"
                        ,"duotou_highrisk_79"
                        ,"duotou_littlerisk_order4"
                        ,"duotou_littlerisk_order5_a5"
                        ,"duotou_littlerisk_order5_a6"])]
#标记实验组和对照组
a['target'] = '运营组'
a.ix[df['tags'].isin(["A1_duotou_callback_720_749"
                        ,"A1_duotou_callback_ge_750"
                        ,"A2_duotou_callback_720_749"
                        ,"A2_duotou_callback_ge_750"
                        ,"A3_duotou_callback_720_754"
                        ,"A3_duotou_callback_ge_755"
                        ,"A4_duotou_callback_720_749"
                        ,"A4_duotou_callback_ge_750"
                        ,"A5_noduotou_callback_720_769"
                        ,"A5_noduotou_callback_ge_770"]), 'target'] = '实验组'

a.ix[df['tags'].isin(["A1_duotou_random_callback"
                       ,"A2_duotou_random_callback"
                       ,"A3_duotou_random_callback"
                       ,"A4_duotou_random_callback"
                       ,"A5_noduotou_random_callback"]), 'target'] = '对照组'

#合并一些类
a['new_tag'] = a['tags']
a.ix[a['tags'].isin(["A3_duotou_callback_720_754"
                    ,"A3_duotou_callback_ge_755"]), 'new_tag'] = 'A3_duotou_callback_ge_720'

a.ix[a['tags'].isin(["A4_duotou_callback_720_749"
                    ,"A4_duotou_callback_ge_750"]), 'new_tag'] = 'A4_duotou_callback_ge_720'

a.ix[a['tags'].isin(["A5_noduotou_callback_720_769"
                    ,"A5_noduotou_callback_ge_770"]), 'new_tag'] = 'A5_noduotou_callback_ge_720'


print a.shape
print a.head()

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:31: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
/Users/xiefei/Library/Python/2.7/lib/python/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

(9043, 15)
            id                         tags   user_id             pt  \
1   3599739198  A5_noduotou_random_callback   1019932  2018-01-23_12
6   3599960133    A2_duotou_random_callback   2477784  2018-01-23_14
7   3599964995  A5_noduotou_random_callback  31659165  2018-01-23_14
10  3600218820  duotou_littlerisk_order5_a5  25066063  2018-01-23_16
13  3600222252  duotou_littlerisk_order5_a5   3923145  2018-01-23_16

             created_at duotou_reject_reson strategy_name  qdscore  \
1   2018-01-23 12:53:01          用户QD分层条件拦截      用户多头回捞测试      825
6   2018-01-23 14:23:13    用户Android多头平台数拦截      用户多头模型回捞      941
7   2018-01-23 14:25:07    用户多头平台数和QD分层条件拦截      用户多头回捞测试      826
10  2018-01-23 16:02:02          用户QD分层条件拦截      用户多头回捞测试      837
13  2018-01-23 16:02:43          用户QD分层条件拦截      用户多头回捞测试      839

   qdscore_level  duotou_score  loan_money  iou_limit  type target  \
1             A5         697.0       900.0    2399.94  week    对照组
6             A1         760.0      2800.0    2800.00  week    对照组
7             A5         698.0      1300.0    2406.87  week    对照组
10            A5         694.0       800.0    1235.00  week    运营组
13            A5         724.0       600.0    1947.87  week    运营组

                        new_tag
1   A5_noduotou_random_callback
6     A2_duotou_random_callback
7   A5_noduotou_random_callback
10  duotou_littlerisk_order5_a5
13  duotou_littlerisk_order5_a5